export const INPUT_NAME = 'INPUT_NAME'
export const INPUT_TITLE = 'INPUT_TITLE'

export const SET_SHOULD_RENDER_JOB_TITLE = 'SET_SHOULD_RENDER_JOB_TITLE'
export const SET_SHOULD_RENDER_FULL_RESUME = 'SET_SHOULD_RENDER_FULL_RESUME'

export const SET_PROGRESS = 'SET_PROGRESS'